BOOTLOADER = caterina

MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
LTO_ENABLE = yes
NKRO_ENABLE = no
CONSOLE_ENABLE = no 

WPM_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

EXTRAFLAGS += -flto
